development:
  adapter: postgresql
  encoding: unicode
  database: spree_demo_development
  pool: 5
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: spree_demo_test
  pool: 5
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: spree_demo_production
  pool: 5
  host: localhost
